[package]
name = "xtask"
version = "1.0.0"
edition.workspace = true

[dependencies]
log = { workspace = true }
tracel-xtask = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
